language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
cache:
  - pip
# command to install dependencies
install:
#  - pip install -r requirements.txt
# command to run tests
  - python setup.py install
script:
#  - pytest # or py.test for Python versions 3.5 and below
  - python ./scripts/test_pycoco.py